[project]
name = 'rapidtables'
description = 'Format/create and print tables from lists of dicts'
classifiers = [
    'Programming Language :: Python :: 2',
    'Programming Language :: Python :: 3',
    'Topic :: Software Development :: Libraries',
    'Topic :: Text Processing',
    'Topic :: Text Processing :: Markup',
]
authors = [
    {name = 'Altertech', email = 'div@altertech.com'}
]
readme = {file = 'README.md', content-type = 'text/markdown'}
license = 'MIT'
license-files = ['LICENSE']
dynamic = ['version']

[project.urls]
'Source' = 'https://github.com/alttch/rapidtables'
'Issues' = 'https://github.com/alttch/rapidtables/issues'

[build-system]
requires = ['setuptools >= 77.0.3']
build-backend = 'setuptools.build_meta'

[tool.setuptools.dynamic.version]
attr = 'rapidtables.__version__'
